# Generated by Django 5.2.5 on 2025-08-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_alter_conversation_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={},
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='buyer_last_read',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='seller_last_read',
        ),
        migrations.RemoveField(
            model_name='message',
            name='attachment',
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
    ]
