# Generated by Django 5.2.5 on 2025-08-30 17:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_alter_conversation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='buyer_last_read',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='conversation',
            name='seller_last_read',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
