# Generated by Django 5.2.5 on 2025-08-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_conversation_buyer_last_read_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='conversation',
            name='buyer_last_read',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='seller_last_read',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
