# Generated by Django 5.2.5 on 2025-08-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_alter_conversation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='buyer_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='seller_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
