# Generated by Django 5.2.5 on 2025-09-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_userblock_userreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_muted_by_buyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_muted_by_seller',
            field=models.BooleanField(default=False),
        ),
    ]
