# Generated by Django 5.2.5 on 2025-09-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_conversation_is_muted_by_buyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read_by_buyer_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='read_by_seller_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
