# Generated by Django 5.2.5 on 2025-09-18 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0009_message_read_by_buyer_at_message_read_by_seller_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='read_by_buyer_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='read_by_seller_at',
        ),
    ]
