# Generated by Django 5.2.5 on 2026-01-01 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('vintageapi', '0004_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.brand'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='item',
            name='colors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('NWT', 'New with tags'), ('LN', 'Like new'), ('G', 'Good'), ('F', 'Fair')], max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='materials',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='item',
            name='styles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(blank=True, to='catalog.tag'),
        ),
    ]
