# Generated by Django 5.2.5 on 2025-08-23 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
    ]
