# Generated by Django 5.2.5 on 2026-01-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributeoption',
            options={'ordering': ['sort_key', 'value']},
        ),
        migrations.AddField(
            model_name='attribute',
            name='max_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='min_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='step',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='attributeoption',
            name='sort_key',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='input_type',
            field=models.CharField(choices=[('enum', 'enum'), ('text', 'text'), ('number', 'number')], default='enum', max_length=12),
        ),
    ]
